---
abstract: 'A glimpse at an Enlightened Perl (DB development).'
author:
  - 'Chris Prather <chris@prather.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-Kensho-DBDev
no_index:
  directory:
    - inc
    - t
requires:
  DBD::SQLite: 0
  DBI: 0
  DBIx::Class: 0
  DBIx::Class::Schema::Loader: 0
  SQL::Translator: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.28
